#!/usr/bin/env python3
"""Check selected GPUCapable dictionary metadata values."""

from __future__ import annotations

import argparse
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


DEFAULT_EXPECTATIONS = {
    "DRIF": 1,
    "MAXAMP": 1,
    "RCOL": 1,
    "ECOL": 1,
    "SCRAPER": 1,
    "KQUAD": 1,
    "KSEXT": 1,
    "KOCT": 1,
    "DQCOR": 1,
    "CSBEND": 1,
    "WAKE": 1,
    "TRWAKE": 1,
    "LSCDRIFT": 1,
    "CSRCSBEND": 1,
    "CSRDRIFT": 1,
    "RFCW": 1,
    "MULT": 0,
    "BMAPXY": 0,
    "CCBEND": 0,
    "UKICKMAP": 0,
    "APCONTOUR": 0,
    "RFDF": 0,
}


def parse_expectation(text: str) -> tuple[str, int]:
    if "=" not in text:
        raise argparse.ArgumentTypeError(f"expected NAME=0 or NAME=1, got {text!r}")
    name, value = text.split("=", 1)
    name = name.strip().upper()
    value = value.strip()
    if not name or value not in {"0", "1"}:
        raise argparse.ArgumentTypeError(f"expected NAME=0 or NAME=1, got {text!r}")
    return name, int(value)


def read_with_sdds2stream(path: Path, sdds2stream: str | None) -> dict[str, int]:
    if not sdds2stream:
        return {}
    proc = subprocess.run(
        [
            sdds2stream,
            str(path),
            "-parameters=ElementType,GPUCapable",
            "-delimiter=\t",
            "-noquotes",
        ],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        return {}

    values: dict[str, int] = {}
    loose_tokens: list[str] = []
    for raw_line in proc.stdout.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        parts = [part.strip() for part in line.split("\t") if part.strip()]
        if len(parts) < 2:
            parts = shlex.split(line)
        if len(parts) >= 2 and parts[1] in {"0", "1"}:
            values[parts[0].upper()] = int(parts[1])
        else:
            loose_tokens.extend(parts)

    for i in range(0, len(loose_tokens) - 1, 2):
        if loose_tokens[i + 1] in {"0", "1"}:
            values[loose_tokens[i].upper()] = int(loose_tokens[i + 1])
    return values


def next_data_line(lines: list[str], index: int) -> tuple[str | None, int]:
    while index < len(lines):
        line = lines[index].strip()
        index += 1
        if not line or line.startswith("!"):
            continue
        return line, index
    return None, index


def first_token(line: str) -> str:
    parts = shlex.split(line)
    return parts[0] if parts else ""


def read_ascii_dictionary(path: Path) -> dict[str, int]:
    lines = path.read_text(errors="replace").splitlines()
    data_index = None
    for i, line in enumerate(lines):
        if line.strip().startswith("&data"):
            data_index = i + 1
            break
    if data_index is None:
        raise ValueError(f"{path} does not look like an SDDS dictionary file")

    values: dict[str, int] = {}
    index = data_index
    while index < len(lines):
        element_line, index = next_data_line(lines, index)
        if element_line is None:
            break
        element = first_token(element_line).upper()
        if not element:
            break

        skipped: list[str] = []
        for _ in range(5):
            value_line, index = next_data_line(lines, index)
            if value_line is None:
                return values
            skipped.append(first_token(value_line))
        gpu_value = skipped[1]
        row_count_line, index = next_data_line(lines, index)
        if row_count_line is None:
            return values
        try:
            row_count = int(first_token(row_count_line))
            values[element] = int(gpu_value)
        except ValueError as exc:
            raise ValueError(f"could not parse dictionary page for {element}") from exc

        index += row_count

    return values


def load_dictionary(path: Path, sdds2stream: str | None) -> dict[str, int]:
    values = read_with_sdds2stream(path, sdds2stream)
    if values:
        return values
    return read_ascii_dictionary(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dictionary", type=Path, help="dictionary.sdds generated by &print_dictionary")
    parser.add_argument("--expect", action="append", type=parse_expectation, default=[], help="expected NAME=0 or NAME=1")
    parser.add_argument("--no-default-expectations", action="store_true", help="only check --expect values")
    parser.add_argument("--sdds2stream", help="path to sdds2stream")
    parser.add_argument("--list", action="store_true", help="print all parsed GPUCapable values")
    args = parser.parse_args()

    sdds2stream = args.sdds2stream or shutil.which("sdds2stream")
    try:
        values = load_dictionary(args.dictionary, sdds2stream)
    except Exception as exc:
        print(f"failed to read {args.dictionary}: {exc}", file=sys.stderr)
        return 2

    if args.list:
        for name in sorted(values):
            print(f"{name}={values[name]}")

    expectations = {} if args.no_default_expectations else dict(DEFAULT_EXPECTATIONS)
    expectations.update(args.expect)

    failures = 0
    for name, expected in sorted(expectations.items()):
        actual = values.get(name)
        if actual is None:
            print(f"FAIL {name}: missing from dictionary")
            failures += 1
        elif actual != expected:
            print(f"FAIL {name}: expected GPUCapable={expected}, found {actual}")
            failures += 1
        else:
            print(f"PASS {name}: GPUCapable={actual}")

    if failures:
        print(f"{failures} GPUCapable metadata check(s) failed")
        return 1
    print(f"all {len(expectations)} GPUCapable metadata check(s) passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
