SDDS_REPO = $(firstword $(wildcard ../../SDDS ../../../../../epics/extensions/src/SDDS))
ifeq ($(SDDS_REPO),)
  $(error SDDS source code not found. Run 'git clone https://github.com/rtsoliday/SDDS.git' next to the elegant repository)
endif

include ../Makefile.rules

PROD = Pelegant
PELEGANT_INSTALL_NAME = Pelegant$(EXEEXT)

Pelegant_SRC = alpha_data.c \
	alpha_matrix.c \
	alter.c \
	amplif.c \
	analyze.c \
	aperture_search.c \
	apple.c \
	bend_matrix.c \
	bratSubroutines.c \
	bunched_beam.c \
	ccbend.c \
	cfgets.c \
	chaosMap.c \
	chbook.c \
	check_duplic.c \
	chrom.c \
	circles.c \
	closed_orbit.c \
	compose_fn.c \
	computeMatricesFromTracking.c \
	compute_centroids.c \
	compute_matrices.c \
	concat_beamline.c \
	concat_mat.c \
	context.c \
	cooler.c \
	copy_particles.c \
	cormon_stats_output.c \
	correct.c \
	corrector_output.c \
	counter.c \
	coupled_twiss.c \
	csbend.c \
	divideElements.c \
	do_tracking.c \
	drand_oag.c \
	elasticScattering.c \
	elegant.c \
	engeCoef.c \
	error.c \
	exactCorrector.c \
	extend_list.c \
	Faddeeva.cc \
	final_props.c \
	find_elem.c \
	floor.c \
	frequencyMap.c \
	frfmode.c \
	fringe.c \
	ftrfmode.c \
	generate_bunch.c \
	get_beamline.c \
	global_settings.c \
	gwig.c \
	GWigSymplecticPass.c \
	ibs_tracking.c \
	ignoreElements.c \
	iirFilter.c \
	inelasticScattering.c \
	insertSCeffects.cc \
	insert_elements.c \
	ionEffects.cc \
	kahan.c \
	kick_poly.c \
	kick_sbend.c \
	kicker.c \
	kickmap.c \
	lgbend.c \
	limit_amplitudes.c \
	link_date.c \
	link_elements.c \
	load_parameters.c \
	lorentz.c \
	lorentzian.c \
	lrwake.c \
	lsc.c \
	mad_parse.c \
	magneticFieldFromGeneralizedGradient.c \
	magneticFieldOffAxisExpansion.c \
	makeInitialParticleEnsemble.c \
	malign_mat.c \
	matrix.c \
	matrixOp.c \
	matrix_output.c \
	matter.c \
	mod_rfca.c \
	modulate.c \
	moments.c \
	momentumAperture.c \
	motion.cc \
	multipole.c \
	noiseGroup.c \
	obstructionData.c \
	optimize.c \
	orbtraj_output.c \
	output_magnets.c \
	particleTunes.c \
	patterns.c \
	pepper_pot.c \
	phase_reference.c \
	pointInsideContour.c \
	poisson.cc \
	poissonBuffer.cc \
	pressureData.c \
	print_line.c \
	quad_matrix.c \
	ramp.c \
	ramp_momentum.c \
	ramped_rfca.c \
	regexCode.cc \
	replace_elements.c \
	response.c \
	rfmode.cc \
	run_rpnexpr.c \
	sample.c \
	sasefel.c \
	sasefelmx.c \
	sdds_beam.c \
	sdds_support.c \
	sdds_support_common.c \
	shrfdf.c \
	simple_rfca.c \
	sliceAnalysis.c \
	slicePoint.c \
	SReffects.c \
	spinUpdate.c \
	subprocess.c \
	taylorSeries.c \
	tfeedback.cc \
	tilt_matrices.c \
	touschekScatter.c \
	trace.c \
	track_data.c \
	track_ramp.c \
	track_rf.c \
	transformBeamWithScript.c \
	transmuteElements.c \
	trfmode.c \
	trimApertureSearchResult.c \
	trwake.c \
	tubend.c \
	tune.c \
	tuneFootprint.c \
	twiss.cc \
	ukickmap.c \
	vary.c \
	wake.c \
	warnings.c \
	zibs.c \
	zlongit.c \
	ztransverse.c \
	findGlobalMinMax.c \
	media_oag.c \
	genetic.c \
	swarm.c

Pelegant_SRC := $(subst .c,.mpi.c,$(Pelegant_SRC))

ifneq ($(wildcard $(DD)../.svn $(DD)../../../../.svn),)
  SVN_VERSION=$(shell svnversion .)
else
  SVN_VERSION=GIT_$(shell git log --oneline | wc -l | sed 's/^[[:space:]]*//')
endif

CFLAGS += -I$(SDDS_REPO)/include -I$(SDDS_REPO)/pgapack -DWL=32 -I$(OBJ_DIR) -DIEEE_MATH -DMINIMIZE_MEMORY -DUSE_KAHAN -DUSE_GSL -DSVN_VERSION=\"$(SVN_VERSION)\" -DUSE_MPI=1 -DSDDS_MPI_IO=1
CCFLAGS += -I$(SDDS_REPO)/include -I$(SDDS_REPO)/pgapack -DWL=32 -I$(OBJ_DIR) -DIEEE_MATH -DMINIMIZE_MEMORY -DUSE_KAHAN -DUSE_GSL -DSVN_VERSION=\"$(SVN_VERSION)\" -DUSE_MPI=1 -DSDDS_MPI_IO=1

ifeq ($(MDEBUG),1)
  CFLAGS += -DMPI_DEBUG=1 -Og
  CCFLAGS += -DMPI_DEBUG=1 -Og
endif

ifeq ($(OS), Linux)
  CC = $(MPI_CC)
  CCC = $(MPI_CCC)
  CFLAGS += -std=gnu11 $(MKL_CFLAG) $(MKL_INCLUDE) $(LAPACK_CFLAG) $(LAPACK_INCLUDE) $(EPICS_EXTENSIONS_GSL_INC_LOCAL)
  CCFLAGS += $(MKL_CFLAG) $(MKL_INCLUDE) $(LAPACK_CFLAG) $(LAPACK_INCLUDE) $(EPICS_EXTENSIONS_GSL_INC_LOCAL)
  LDFLAGS := -L$(SDDS_REPO)/lib/$(OS)-$(ARCH) -fopenmp -Bstatic -static-libgcc -rdynamic -m64
  PROD_SYS_LIBS := $(LZMA_LIB) $(GSL_LIB) $(GSLCBLAS_LIB) $(Z_LIB) $(FFTW3_LIB)  $(MKL_LIB) $(LAPACK_LIB) $(PROD_SYS_LIBS)
  PROD_LIBS_SDDS = -lpgapack -lmdbcommon -lmatlib -lfftpack -lSDDS1mpi -lnamelist -lrpnlib -lmdbmth -lmdblib
endif

ifeq ($(OS), Darwin)
  CC = $(MPI_CC)
  CCC = $(MPI_CCC)
  $(info $(CC))
  CFLAGS += -DCLAPACK
  CCFLAGS += -DCLAPACK
  LDFLAGS := -L$(SDDS_REPO)/lib/$(OS)-$(ARCH) $(LDFLAGS)
  PROD_SYS_LIBS := -framework Accelerate $(LZMA_LIB) $(GSL_LIB) $(GSLCBLAS_LIB) $(Z_LIB) $(FFTW3_LIB) $(PROD_SYS_LIBS)
  PROD_LIBS_SDDS = -lpgapack -lmdbcommon -lmatlib -lfftpack -lSDDS1mpi -lnamelist -lrpnlib -lmdbmth -lmdblib
endif

ifeq ($(OS), Windows)
  CFLAGS += -I$(SDDS_REPO)/lzma -I../../gsl $(MKL_CFLAG) $(MKL_INCLUDE) $(MKL_INCLUDE)/fftw $(WIN_MPI_INC) -wd4018 -wd4244 -wd4267 -wd4311
  CCFLAGS += -I$(SDDS_REPO)/lzma -I../../gsl $(MKL_CFLAG) $(MKL_INCLUDE) $(MKL_INCLUDE)/fftw $(WIN_MPI_INC) -wd4018 -wd4244 -wd4267 -wd4311
  PROD_SYS_LIBS := gsl.lib gslcblas.lib $(MKL_LIB) $(WIN_MPI_LIB) $(PROD_SYS_LIBS)
  PROD_LIBS_SDDS = pgapack.lib mdbcommon.lib matlib.lib fftpack.lib SDDS1mpi.lib namelist.lib rpnlib.lib mdbmth.lib mdblib.lib lzma.lib z.lib
  LIB_LINK_DIRS += -LIBPATH:$(SDDS_REPO)/lib/$(OS)-$(ARCH)
endif

CUDA_REQUESTED := $(filter 1 yes YES true TRUE on ON,$(HAVE_CUDA) $(HAVE_GPU))
ifneq ($(CUDA_REQUESTED),)
  HAVE_CUDA := 1
  HAVE_GPU := 1
  PELEGANT_INSTALL_NAME = gpu-Pelegant$(EXEEXT)
  CUDA_NVCC_FROM_PATH := $(shell command -v nvcc 2>/dev/null)
  CUDA_NVCC_COMMON := /usr/local/cuda-12.4/bin/nvcc /usr/local/cuda/bin/nvcc
  CUDA_NVCC_VERSIONED := $(sort $(wildcard /usr/local/cuda-*/bin/nvcc))
  ifeq ($(strip $(NVCC)),)
    NVCC := $(firstword $(CUDA_NVCC_FROM_PATH) $(wildcard $(CUDA_NVCC_COMMON)) $(CUDA_NVCC_VERSIONED))
  endif
  ifeq ($(strip $(NVCC)),)
    ifeq ($(filter clean distclean,$(MAKECMDGOALS)),)
      $(error CUDA support requested for Pelegant, but nvcc was not found. Set NVCC=/path/to/nvcc, for example NVCC=/usr/local/cuda-12.4/bin/nvcc)
    endif
  endif
  CUDA_HOME ?= $(patsubst %/bin/nvcc,%,$(NVCC))
  CUDA_ARCH ?= sm_86
  OBJ_DIR := $(OBJ_DIR).gpu.mpi
  BIN_DIR := $(BIN_DIR)-gpu
  ifeq ($(GPU_VERIFY),1)
    OBJ_DIR := $(OBJ_DIR).verify
    BIN_DIR := $(BIN_DIR)-verify
    CFLAGS += -DGPU_VERIFY=1
    CCFLAGS += -DGPU_VERIFY=1
    NVCCFLAGS += -DGPU_VERIFY=1
  endif
  CFLAGS += -DHAVE_GPU=1 -Igpu -I$(CUDA_HOME)/include
  CCFLAGS += -DHAVE_GPU=1 -Igpu -I$(CUDA_HOME)/include
  NVCCFLAGS += -O3 -g -arch=$(CUDA_ARCH) --fmad=false -Xcompiler -fPIC -I$(SDDS_REPO)/include -I$(SDDS_REPO)/pgapack -I$(OBJ_DIR) -Igpu -I$(CUDA_HOME)/include -DIEEE_MATH -DMINIMIZE_MEMORY -DUSE_KAHAN -DUSE_GSL -DUSE_MPI=1 -DSDDS_MPI_IO=1 -DWL=32 -DSVN_VERSION=\"$(SVN_VERSION)\" -DHAVE_GPU=1
  NVCCDEPFLAGS ?= $(DEPFLAGS)
  LDFLAGS += -L$(CUDA_HOME)/lib64 -Wl,-rpath,$(CUDA_HOME)/lib64
  PROD_SYS_LIBS += -Wl,-Bdynamic -lcudart
  Pelegant_SRC += gpu/gpu_stub.mpi.c gpu/gpu_cuda_runtime.mpi.cu
endif

include ../Makefile.build

$(OBJ_DIR)/Pelegant$(EXEEXT): $(Pelegant_OBJS) $(PROD_DEPS)
	$(LINKEXE) $(OUTPUTEXE) $(Pelegant_OBJS) $(LDFLAGS) $(LIB_LINK_DIRS) $(PROD_LIBS) $(PROD_LIBS_SDDS) $(PROD_SYS_LIBS)
	cp -f $@ $(BIN_DIR)/$(PELEGANT_INSTALL_NAME)
	@if [ -n "$(EPICS_BIN_DIR)" ]; then echo cp -f $@ $(EPICS_BIN_DIR)/$(PELEGANT_INSTALL_NAME); fi
	@if [ -n "$(EPICS_BIN_DIR)" ]; then cp -f $@ $(EPICS_BIN_DIR)/$(PELEGANT_INSTALL_NAME); fi

$(OBJ_DIR)/%.mpi.$(OBJEXT): %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(if $(filter $(notdir $<), $(LIBRARY_SRC)),$(LIBRARY_CFLAGS)) -c $< $(OUTPUT)
$(OBJ_DIR)/%.mpi.$(OBJEXT): %.cc
	@mkdir -p $(dir $@)
	$(CCC) $(CCFLAGS) $(if $(filter $(notdir $<), $(LIBRARY_SRC)),$(LIBRARY_CCFLAGS)) -c $< $(OUTPUT)
$(OBJ_DIR)/%.mpi.$(OBJEXT): %.cu
	@mkdir -p $(dir $@)
	$(NVCC) $(NVCCFLAGS) $(NVCCDEPFLAGS) -c $< $(OUTPUT)

$(OBJ_DIR)/insertSCeffects.mpi.$(OBJEXT): $(OBJ_DIR)/insertSCeffects.h

$(OBJ_DIR)/insertSCeffects.h: insertSCeffects.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables insertSCeffects.nl $(OBJ_DIR)/insertSCeffects.h

$(OBJ_DIR)/amplif.mpi.$(OBJEXT): $(OBJ_DIR)/amplif.h

$(OBJ_DIR)/amplif.h: amplif.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables amplif.nl $(OBJ_DIR)/amplif.h

$(OBJ_DIR)/momentumAperture.mpi.$(OBJEXT): $(OBJ_DIR)/momentumAperture.h

$(OBJ_DIR)/momentumAperture.h: momentumAperture.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables momentumAperture.nl $(OBJ_DIR)/momentumAperture.h

$(OBJ_DIR)/sasefel.mpi.$(OBJEXT): $(OBJ_DIR)/sasefel.h

$(OBJ_DIR)/sasefel.h: sasefel.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables sasefel.nl $(OBJ_DIR)/sasefel.h

$(OBJ_DIR)/matrix_output.mpi.$(OBJEXT): $(OBJ_DIR)/matrix_output.h

$(OBJ_DIR)/matrix_output.h: matrix_output.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables matrix_output.nl $(OBJ_DIR)/matrix_output.h

$(OBJ_DIR)/insert_elements.mpi.$(OBJEXT): $(OBJ_DIR)/insert_elements.h

$(OBJ_DIR)/insert_elements.h: insert_elements.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables insert_elements.nl $(OBJ_DIR)/insert_elements.h

$(OBJ_DIR)/analyze.mpi.$(OBJEXT): $(OBJ_DIR)/analyze.h

$(OBJ_DIR)/analyze.h: analyze.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables analyze.nl $(OBJ_DIR)/analyze.h

$(OBJ_DIR)/replace_elements.mpi.$(OBJEXT): $(OBJ_DIR)/replace_elements.h

$(OBJ_DIR)/replace_elements.h: replace_elements.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables replace_elements.nl $(OBJ_DIR)/replace_elements.h

$(OBJ_DIR)/tune.mpi.$(OBJEXT): $(OBJ_DIR)/tune.h

$(OBJ_DIR)/tune.h: tune.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables tune.nl $(OBJ_DIR)/tune.h

$(OBJ_DIR)/floor.mpi.$(OBJEXT): $(OBJ_DIR)/floor.h

$(OBJ_DIR)/floor.h: floor.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables floor.nl $(OBJ_DIR)/floor.h

$(OBJ_DIR)/run_rpnexpr.mpi.$(OBJEXT): $(OBJ_DIR)/run_rpnexpr.h

$(OBJ_DIR)/run_rpnexpr.h: run_rpnexpr.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables run_rpnexpr.nl $(OBJ_DIR)/run_rpnexpr.h

$(OBJ_DIR)/ionEffects.mpi.$(OBJEXT): $(OBJ_DIR)/ionEffects.h

$(OBJ_DIR)/ionEffects.h: ionEffects.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables ionEffects.nl $(OBJ_DIR)/ionEffects.h

$(OBJ_DIR)/subprocess.mpi.$(OBJEXT): $(OBJ_DIR)/subprocess.h

$(OBJ_DIR)/subprocess.h: subprocess.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables subprocess.nl $(OBJ_DIR)/subprocess.h

$(OBJ_DIR)/trace.mpi.$(OBJEXT): $(OBJ_DIR)/trace.h

$(OBJ_DIR)/trace.h: trace.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables trace.nl $(OBJ_DIR)/trace.h

$(OBJ_DIR)/divideElements.mpi.$(OBJEXT): $(OBJ_DIR)/divideElements.h

$(OBJ_DIR)/divideElements.h: divideElements.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables divideElements.nl $(OBJ_DIR)/divideElements.h

$(OBJ_DIR)/load_parameters.mpi.$(OBJEXT): $(OBJ_DIR)/load_parameters.h

$(OBJ_DIR)/load_parameters.h: load_parameters.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables load_parameters.nl $(OBJ_DIR)/load_parameters.h

$(OBJ_DIR)/optim_covariable.mpi.$(OBJEXT): $(OBJ_DIR)/optim_covariable.h

$(OBJ_DIR)/optim_covariable.h: optim_covariable.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables optim_covariable.nl $(OBJ_DIR)/optim_covariable.h

$(OBJ_DIR)/ignoreElements.mpi.$(OBJEXT): $(OBJ_DIR)/ignoreElements.h

$(OBJ_DIR)/ignoreElements.h: ignoreElements.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables ignoreElements.nl $(OBJ_DIR)/ignoreElements.h

$(OBJ_DIR)/moments.mpi.$(OBJEXT): $(OBJ_DIR)/moments.h

$(OBJ_DIR)/moments.h: moments.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables moments.nl $(OBJ_DIR)/moments.h

$(OBJ_DIR)/chaosMap.mpi.$(OBJEXT): $(OBJ_DIR)/chaosMap.h

$(OBJ_DIR)/chaosMap.h: chaosMap.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables chaosMap.nl $(OBJ_DIR)/chaosMap.h

$(OBJ_DIR)/response.mpi.$(OBJEXT): $(OBJ_DIR)/response.h

$(OBJ_DIR)/response.h: response.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables response.nl $(OBJ_DIR)/response.h

$(OBJ_DIR)/correct.mpi.$(OBJEXT): $(OBJ_DIR)/correct.h $(OBJ_DIR)/steer_elem.h 

$(OBJ_DIR)/correct.h: correct.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables correct.nl $(OBJ_DIR)/correct.h

$(OBJ_DIR)/closed_orbit.mpi.$(OBJEXT): $(OBJ_DIR)/closed_orbit.h

$(OBJ_DIR)/closed_orbit.h: closed_orbit.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables closed_orbit.nl $(OBJ_DIR)/closed_orbit.h

$(OBJ_DIR)/twiss.mpi.$(OBJEXT): $(OBJ_DIR)/twiss.h

$(OBJ_DIR)/twiss.h: twiss.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables twiss.nl $(OBJ_DIR)/twiss.h

$(OBJ_DIR)/link_elements.mpi.$(OBJEXT): $(OBJ_DIR)/link_elements.h

$(OBJ_DIR)/link_elements.h: link_elements.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables link_elements.nl $(OBJ_DIR)/link_elements.h

$(OBJ_DIR)/chrom.mpi.$(OBJEXT): $(OBJ_DIR)/chrom.h

$(OBJ_DIR)/chrom.h: chrom.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables chrom.nl $(OBJ_DIR)/chrom.h

$(OBJ_DIR)/touschekScatter.mpi.$(OBJEXT): $(OBJ_DIR)/touschekScatter.h

$(OBJ_DIR)/touschekScatter.h: touschekScatter.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables touschekScatter.nl $(OBJ_DIR)/touschekScatter.h

$(OBJ_DIR)/transmuteElements.mpi.$(OBJEXT): $(OBJ_DIR)/transmuteElements.h

$(OBJ_DIR)/transmuteElements.h: transmuteElements.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables transmuteElements.nl $(OBJ_DIR)/transmuteElements.h

$(OBJ_DIR)/sdds_beam.mpi.$(OBJEXT): $(OBJ_DIR)/sdds_beam.h

$(OBJ_DIR)/sdds_beam.h: sdds_beam.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables sdds_beam.nl $(OBJ_DIR)/sdds_beam.h

$(OBJ_DIR)/aperture_search.mpi.$(OBJEXT): $(OBJ_DIR)/aperture_search.h

$(OBJ_DIR)/aperture_search.h: aperture_search.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables aperture_search.nl $(OBJ_DIR)/aperture_search.h

$(OBJ_DIR)/aperture_data.mpi.$(OBJEXT): $(OBJ_DIR)/aperture_data.h

$(OBJ_DIR)/aperture_data.h: aperture_data.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables aperture_data.nl $(OBJ_DIR)/aperture_data.h

$(OBJ_DIR)/tuneFootprint.mpi.$(OBJEXT): $(OBJ_DIR)/tuneFootprint.h

$(OBJ_DIR)/tuneFootprint.h: tuneFootprint.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables tuneFootprint.nl $(OBJ_DIR)/tuneFootprint.h

$(OBJ_DIR)/vary.mpi.$(OBJEXT): $(OBJ_DIR)/vary.h

$(OBJ_DIR)/vary.h: vary.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables vary.nl $(OBJ_DIR)/vary.h

$(OBJ_DIR)/steer_elem.mpi.$(OBJEXT): $(OBJ_DIR)/steer_elem.h

$(OBJ_DIR)/steer_elem.h: steer_elem.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables steer_elem.nl $(OBJ_DIR)/steer_elem.h

$(OBJ_DIR)/error.mpi.$(OBJEXT): $(OBJ_DIR)/error.h

$(OBJ_DIR)/error.h: error.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables error.nl $(OBJ_DIR)/error.h

$(OBJ_DIR)/bunched_beam.mpi.$(OBJEXT): $(OBJ_DIR)/bunched_beam.h $(OBJ_DIR)/bunched_beam2.h 

$(OBJ_DIR)/bunched_beam.h: bunched_beam.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables bunched_beam.nl $(OBJ_DIR)/bunched_beam.h

$(OBJ_DIR)/ramp.mpi.$(OBJEXT): $(OBJ_DIR)/ramp.h

$(OBJ_DIR)/ramp.h: ramp.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables ramp.nl $(OBJ_DIR)/ramp.h

$(OBJ_DIR)/inelasticScattering.mpi.$(OBJEXT): $(OBJ_DIR)/inelasticScattering.h

$(OBJ_DIR)/inelasticScattering.h: inelasticScattering.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables inelasticScattering.nl $(OBJ_DIR)/inelasticScattering.h

$(OBJ_DIR)/bunched_beam2.mpi.$(OBJEXT): $(OBJ_DIR)/bunched_beam2.h

$(OBJ_DIR)/bunched_beam2.h: bunched_beam2.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables bunched_beam2.nl $(OBJ_DIR)/bunched_beam2.h

$(OBJ_DIR)/optimize.mpi.$(OBJEXT): $(OBJ_DIR)/optimize.h $(OBJ_DIR)/optim_covariable.h

$(OBJ_DIR)/optimize.h: optimize.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables optimize.nl $(OBJ_DIR)/optimize.h

$(OBJ_DIR)/elasticScattering.mpi.$(OBJEXT): $(OBJ_DIR)/elasticScattering.h

$(OBJ_DIR)/elasticScattering.h: elasticScattering.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables elasticScattering.nl $(OBJ_DIR)/elasticScattering.h

$(OBJ_DIR)/modulate.mpi.$(OBJEXT): $(OBJ_DIR)/modulate.h

$(OBJ_DIR)/modulate.h: modulate.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables modulate.nl $(OBJ_DIR)/modulate.h

$(OBJ_DIR)/fitTraces.mpi.$(OBJEXT): $(OBJ_DIR)/fitTraces.h

$(OBJ_DIR)/fitTraces.h: fitTraces.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables fitTraces.nl $(OBJ_DIR)/fitTraces.h

$(OBJ_DIR)/frequencyMap.mpi.$(OBJEXT): $(OBJ_DIR)/frequencyMap.h

$(OBJ_DIR)/frequencyMap.h: frequencyMap.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables frequencyMap.nl $(OBJ_DIR)/frequencyMap.h

$(OBJ_DIR)/sliceAnalysis.mpi.$(OBJEXT): $(OBJ_DIR)/sliceAnalysis.h

$(OBJ_DIR)/sliceAnalysis.h: sliceAnalysis.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables sliceAnalysis.nl $(OBJ_DIR)/sliceAnalysis.h

$(OBJ_DIR)/get_beamline.mpi.$(OBJEXT): $(OBJ_DIR)/save_lattice.h

$(OBJ_DIR)/save_lattice.mpi.$(OBJEXT): $(OBJ_DIR)/save_lattice.h

$(OBJ_DIR)/save_lattice.h: save_lattice.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables save_lattice.nl $(OBJ_DIR)/save_lattice.h

$(OBJ_DIR)/alter.mpi.$(OBJEXT): $(OBJ_DIR)/alter.h

$(OBJ_DIR)/alter.h: alter.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables alter.nl $(OBJ_DIR)/alter.h

$(OBJ_DIR)/elegant.mpi.$(OBJEXT): $(OBJ_DIR)/elegant.h $(OBJ_DIR)/aperture_data.h

$(OBJ_DIR)/elegant.h: elegant.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp elegant.nl $(OBJ_DIR)/elegant.h

$(OBJ_DIR)/coupled_twiss.mpi.$(OBJEXT): $(OBJ_DIR)/coupled_twiss.h

$(OBJ_DIR)/coupled_twiss.h: coupled_twiss.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables coupled_twiss.nl $(OBJ_DIR)/coupled_twiss.h

$(OBJ_DIR)/obstructionData.mpi.$(OBJEXT): $(OBJ_DIR)/obstructionData.h

$(OBJ_DIR)/obstructionData.h: obstructionData.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables obstructionData.nl $(OBJ_DIR)/obstructionData.h

$(OBJ_DIR)/global_settings.mpi.$(OBJEXT): $(OBJ_DIR)/global_settings.h

$(OBJ_DIR)/global_settings.h: global_settings.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables global_settings.nl $(OBJ_DIR)/global_settings.h

$(OBJ_DIR)/particleTunes.mpi.$(OBJEXT): $(OBJ_DIR)/particleTunes.h

$(OBJ_DIR)/particleTunes.h: particleTunes.nl
	$(SDDS_REPO)/bin/$(OS)-$(ARCH)/nlpp -suppressSummaryVariables particleTunes.nl $(OBJ_DIR)/particleTunes.h
